[package]
name = "autoclicker"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.27"
egui = "0.27"
enigo = "0.2"
device_query = "4.0.1"

[target.'cfg(windows)'.build-dependencies]
image = "0.24"
winres = "0.1"